#!/bin/sh
#
# LiveCD hardware detection rc script
# Copyright (C) 2002-2003, Jaco Greeff <jaco@linuxminicd.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# Adapted for mklivecd from the MiniCD (http://www.linuxminicd.org> hwdetect rc script
#
# File version: $Id: hwdetect,v 1.2 2003/09/25 08:40:25 jaco Exp $
#

### Source function library.
. /etc/rc.d/init.d/functions

### handle the passed option
case $1 in
	start)
		OLD_ARGS="$INITLOG_ARGS"
		INITLOG_ARGS=
		if [ -e /usr/sbin/hwdetect ]; then
			action "Detecting/configuring hardware:" "/usr/sbin/hwdetect"
		else
			action "Detecting/configuring hardware:" "/initrd/usr/sbin/hwdetect"
		fi
		INITLOG_ARGS="$OLD_ARGS"
		;;

	stop)
		;;

	status)
		;;

	reload)
		;;

	restart)
		;;

	*)
		gprintf "Usage: %s\n" "$(basename $0) {start}"
		;;
esac
exit 0

### hwdetect ends here
